name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Build and Publish to Docker Hub
      uses:  azure/docker-login@v1
      with:
        username: aksrini1980
        password: ${{ secrets.GITHUB_DOCKERHUB_TOKEN }}
    - run: |
        pwd
        ls -ltr
        docker build . -t aksrini1980/opencv:${{ github.sha }}
        docker tag aksrini1980/opencv:${{ github.sha }} aksrini1980/opencv:0.10.0
        docker push aksrini1980/opencv:${{ github.sha }} aksrini1980/opencv:0.10.0

